### ISSUE TITLE
Beach ball of death

### ISSUE THREAD

**Issue by mallowigi** [JetBrains/ruby-type-inference#40]
Just tried this plugin and it caused me the "beach ball of death" everytime I open autocomplete or find usages.

**Comment by nikitabobko** [comment]
Thanks for feedback. Can you provide more information? What exactly happens when you call autocompletion?

**Comment by nikitabobko** [comment]
As a good start you could ensure that you have latest installed version of [arg-scanner](https://rubygems.org/gems/arg_scanner) and latest version of plugin

**Comment by nikitabobko** [comment]
I guess your issue is the same as: https://youtrack.jetbrains.com/issue/RUBY-25433 Fix is on the way

**Comment by slrls** [comment]
I started getting this issue as well after upgrading IntelliJ to 2019.3.1 from 2019.2.4. Using the plugin build you posted in the JetBrains issue tracker fixed it for me. Thanks!

**Comment by smeevil** [comment]
> I guess your issue is the same as: https://youtrack.jetbrains.com/issue/RUBY-25433 Fix is on the way

Hi,

I was wondering if you would have a status update on this ?

**Comment by nikitabobko** [comment]
> I was wondering if you would have a status update on this ?

YouTrack status is that issue is fixed. And it's relevant status :) If you still experience this problem then write to issue in YouTrack or here attaching your logs and thread dumps
